### ISSUE TITLE
Breadcrumbs show placeholder before data are loaded

### ISSUE THREAD

**Issue by tomaszs** [rajaramtt/ng7-dynamic-breadcrumb#16]
When i use:

"{{dynamicText}} page" as a label in routing definition

And set dynamicText with:

`this.ng7MatBreadcrumbService.updateBreadcrumbLabels(breadcrumb);`

in a component where breadcrumb is:

`{dynamicText: 'abc'}`

after loading the data, than:

1. "{{dynamicText}] page" shows up literally (with the placeholder being visible on the screen
2. When data are loaded {[dynamicText}} is replaced with the proper dynamicText

Expected result:

{{dynamicText}} placeholder is not visible

Current result:

it is

Moreover calling:

`this.ng7MatBreadcrumbService.updateBreadcrumbLabels(breadcrumb);`

in constructor with empty dynamicText causes second call with data not update the dynamicText

**Comment by rajaramtt** [comment]
Out of the scope, No longer supported by the author this future, If anyone interested, Please submit PR
