### ISSUE TITLE
.updateBreadcrumb() not working after first call

### ISSUE THREAD

**Issue by acelsosoares** [rajaramtt/ng7-dynamic-breadcrumb#19]
I am developing a website with i18n module to translate between two languages.
This module doesn't support translation, so i tried to workaround using the method .updateBreadcrumb() every time i change the language and i pass respective labels like .updateBreadcrumb({"labelXYZ": "langENG"}) or .updateBreadcrumb({"labelXYZ": "langPT"})..

When i enter in a new page, the updateBreadcrumb is called and updates the the breadcrumb fine. But when i change the language in the menu i made, a language change event is triggered and i call again the method .updateBreadcrumb (with other language labels), but this time the breadCrumb doesn't change and continues with the old language.

If i change to other page, the breadcrumb updates to the new language selected before. But if i change again the language through menu and call .updateBreadcrumb again, nothing happens.

**Comment by joaosousafranco** [comment]
This is still happening in the latest version, will u include it at any point?
