### ISSUE TITLE
[Feature] Style injection

### ISSUE THREAD

**Issue by canpan14** [rajaramtt/ng7-dynamic-breadcrumb#2]
Love the project!
It would be awesome if you could inject a class(es) and it would apply it to the component. Right now the main way to change the styling is to use ng-deep which is deprecated or to add styles to the global class. Talking about the angular one specifically here. Might apply to the others.

(I know you can mess with view encapsulation but that causes other disliked side effects).

**Comment by carlba** [comment]
@canpan14: CAn you provide a sample of how you managed to style it?

**Comment by canpan14** [comment]
@carlba Sure =) I added this to my projects main style.scss
You could add whatever css you want in there though.

app-ng7-mat-breadcrumb {
  .mat-toolbar {
    background-color: inherit !important;
  }
}

**Comment by rajaramtt** [comment]
Out of the scope, No longer supported by the author this future, If anyone interested, Please submit PR
