### ISSUE TITLE
not working under "children"

### ISSUE THREAD

**Issue by mohamedmezlini** [rajaramtt/ng7-dynamic-breadcrumb#20]
Now, I use this package to develop my website. 

First problem: can't use the Angular propriety **children** and if I use it breadcrumb generate error.
Second problem: when I refresh my page, breadcrumb is empty

thank you for this work

**Comment by rajaramtt** [comment]
@mohamedmezlini 

If possible Please create stackblitz example link!.

**Comment by mohamedmezlini** [comment]
@rajaramtt 
Please check this [stackblitz link](https://stackblitz.com/edit/angular-ivy-iaympr?file=src%2Fapp%2Fbook%2Fbook.component.ts)**

**Comment by rajaramtt** [comment]
Out of the scope, No longer supported by the author this future, If anyone interested, Please submit PR
