### ISSUE TITLE
url params not working for child routes

### ISSUE THREAD

**Issue by tahir-jamil** [rajaramtt/ng7-dynamic-breadcrumb#22]
i want to show id like you have explained in sample but its not working
```
{
    path: 'page1/:pageOneID/page2/:pageTwoID',
    component: Page2Component,
    data: {
      title: 'page2', 
      breadcrumb: [
        {
          label: 'page {{pageOneID}}',// pageOneID Parameter value will be add 
          url: '/page1/:pageOneID'
        },
        {
          label: 'page {{pageTwoID}}',// pageTwoID Parameter value will be add 
          url: ''
        }
      ]
    },
  },
```

at the place of **pageOneID** i want to show actual number instead of text

The url for this image is **http://localhost:49158/products/1127**
![Screenshot 2020-05-30 at 5 42 48 PM](https://user-images.githubusercontent.com/40952630/83328523-05da9e00-a29d-11ea-8eaf-a56e7959d364.png)
it should be like **products/1127**

**Comment by rajaramtt** [comment]
If possible Please create stackblitz example link!.

**Comment by tahir-jamil** [comment]
i have fixed this issue but the problem comes with children routes
hear is the link 
https://stackblitz.com/edit/ng-dynamic-breadcrumb-gqfma2?file=src%2Fapp%2Fapp-routing.module.ts

**Comment by zeesulehria** [comment]
@rajaramtt any help with this please?

**Comment by rajaramtt** [comment]
Out of the scope, No longer supported by the author this future, If anyone interested, Please submit PR
