### ISSUE TITLE
Issue witch CSS/Input parameters

### ISSUE THREAD

**Issue by Mikus921** [rajaramtt/ng7-dynamic-breadcrumb#26]
Hi guys,

I have just implemented ng7-bootstrap-breadcrumb but i can't edit the style!

I have tried 2 ways:

1) By CSS's selectors, but I can't find a right one;
2) I can't use Input parameters by Ng7BootstrapBreadcrumbService even if I set my parameters in my node_module.

Someone can help me!? Thanks!

P.S, It's amazing project!

**Comment by Mikus921** [comment]
![Immagine](https://user-images.githubusercontent.com/57632255/91091995-abf93280-e657-11ea-9cac-065efd80aee5.png)

**Comment by rajaramtt** [comment]
Pls  check  https://github.com/rajaramtt/ng7-dynamic-breadcrumb/issues/2#issuecomment-526187168
