### ISSUE TITLE
[Feature] set dynamicText by queryParams/public property

### ISSUE THREAD

**Issue by b4p3p** [rajaramtt/ng7-dynamic-breadcrumb#3]
1) can you set dynamicText by queryParams?

Ex:
```
this.router.navigate(['/products', 10], { queryParams: { productName: 'My product name' } });
```
will be 'My product name'  in breadcrumb

2) can you set dynamicText by public property?

Ex:
```
breadcrumb: [
   { label: '{{CustomText}}',  url: '' }
]
```
and in component
```
export class MyComponent {
   ....
   public get CustomText(){
      return this.blabla.CustomProperty
   }
   ....
}
```

**Comment by rajaramtt** [comment]
Yes. I'll try to implement the next release!.

**Comment by rajaramtt** [comment]
Out of the scope, No longer supported by the author this future, If anyone interested, Please submit PR
