### ISSUE TITLE
Breadcrumb as a dropdown

### ISSUE THREAD

**Issue by alpesh1988** [rajaramtt/ng7-dynamic-breadcrumb#33]
Hello Raja,

Great job!, loved using this module.

Just one question: How is it possible to have a dropdown in breadcrumb something similar to this ?

**Breadcrumb1** / **Breadcrumb2** / Breadcrumb3 (dropdown)

where Breadcrumb3 is a dropdown  with multiple selections.

Do you have any plan to incorporate this feature ?

Regards,
Alpesh

**Comment by rajaramtt** [comment]
Out of the scope, No longer supported by the author this future, If anyone interested, Please submit PR
