### ISSUE TITLE
Click on breadcrumb link,my page url is changing.

### ISSUE THREAD

**Issue by udaykumar235** [rajaramtt/ng7-dynamic-breadcrumb#34]
How to avoid url change  when i click on bread brumb link
![Untitled](https://user-images.githubusercontent.com/6941147/111437246-e11abe80-8728-11eb-94a6-1228ffb8cc95.png)

**Comment by rajaramtt** [comment]
@udaykumar235 It's not  ng7-dynamic-breadcrumb issue!.    Need to work with   skipLocationChange 

https://angular.io/api/router/NavigationBehaviorOptions#skipLocationChange


Out of the scope, No longer supported by the author this future, If anyone interested, Please submit PR
