### ISSUE TITLE
[Feature] internationalization - integration with @ngx-translate

### ISSUE THREAD

**Issue by b4p3p** [rajaramtt/ng7-dynamic-breadcrumb#4]
in our project, we used @ngx-translate
is very usefull specify in router config a field like "labeli18n" that will translate with 
translator.instant("labeli18n") function

Ex:
```
breadcrumb: [
  { labeli18n: "permissions", url: '/main/controlpanel/users' },
]
```

will be
translator.instant("labelKey") =>
permissions -> Permessi in Italian
permissions -> Permissions in English

thank you for your plugin and good work

**Comment by rajaramtt** [comment]
Yes. This will be the next feature

**Comment by Hesesses** [comment]
Thank you @rajaramtt for this great plugin!

Do you have any estimates when the ngx-translate support would be implemented? 🙏

**Comment by rajaramtt** [comment]
I'll try to implement it during the next month. But I do not promise :)

**Comment by Guanaco77** [comment]
First thx for your work bro !

Any news about this new feature ?

**Comment by rajaramtt** [comment]
Hi @Guanaco77 ,

I have been a little bit busy with my professional development work, unable to check your issues.  I will update you once it has done.

Thanks for using ng7-dynamic-breadcrumb , Happy Coding.

**Comment by sagar-1987** [comment]
Hi @rajaramtt ,
Even i am facing same similar issue wanted to translate the breadcrumb labels to different language , Can you please suggest how can this be done in this plugin . Thanks in Advance

**Comment by rajaramtt** [comment]
Yes. This will be the next feature

**Comment by rajaramtt** [comment]
@b4p3p  @Hesesses  @Guanaco77  @sagar-1987 

Hi,  If possible can you please create a stackblitz.com issue reference for me!.

**Comment by rajaramtt** [comment]
Out of the scope, No longer supported by the author this future, If anyone interested, Please submit PR
