### ISSUE TITLE
level2 navigation issue

### ISSUE THREAD

**Issue by klmuralimohan** [rajaramtt/ng7-dynamic-breadcrumb#7]
Kindly provide your inputs on this issue https://stackoverflow.com/questions/56488509/ng7-dynamic-breadcrum-issue

**Comment by rajaramtt** [comment]
@klmuralimohan Please create [stackblitz](https://stackblitz.com) example

**Comment by rajaramtt** [comment]
@klmuralimohan  New feature has been implemented available in [ng-dynamic-breadcrumb](https://www.npmjs.com/package/ng-dynamic-breadcrumb), please check and let me know if there is any issue.

**Update the Breadcrumb using NgDynamicBreadcrumbService**
```
import { NgDynamicBreadcrumbService } from 'ng-dynamic-breadcrumb';
constructor(private ngDynamicBreadcrumbService: NgDynamicBreadcrumbService) { }
 
  updateBreadcrumb(): void {
    const breadcrumbs  =  [
      {
        label: 'page {{pageOneID}}',
        url: '/page1/:pageOneID'
      },
      {
        label: 'page {{pageTwoID}}',
        url: 'page1/:pageOneID/page2/:pageTwoID'
      },
      {
        label: 'page {{pageThreeID}}',
        url: 'page1/:pageOneID/page2/:pageTwoID/page3/:pageThreeID'
      },
      {
        label: 'Update Breadcrumb',
        url: ''
      }
    ];
    this.ngDynamicBreadcrumbService.updateBreadcrumb(breadcrumbs);
  }

```
Stackblitz Demo URL: [https://ng-dynamic-breadcrumb.stackblitz.io/page1/1/page2/2/page3/3](https://ng-dynamic-breadcrumb.stackblitz.io/page1/1/page2/2/page3/3)

NPM avilable version: https://www.npmjs.com/package/ng-dynamic-breadcrumb/v/2.0.1
