### ISSUE TITLE
[BUG] Breadcrumb.map is not a function

### ISSUE THREAD

**Issue by r-hannuschka** [rajaramtt/ng7-dynamic-breadcrumb#9]
By default i simple installed the npm module without define any breadcrumbs, but this leads to an error:

![image](https://user-images.githubusercontent.com/25415574/61874281-4c76a380-aee8-11e9-8030-8c48b8a92a33.png)

This is thrown in [BreadCrumbComponent:75](https://github.com/rajaramtt/ng7-dynamic-breadcrumb/blob/56300a6807253cc05718b2ee4284a3056eb92873/projects/ng-dynamic-breadcrumb/src/lib/ng-dynamic-breadcrumb.component.ts#L75) 

Simple to reproduce, dont add any breadcrumbs, this will call update data with newBreadCrumb as null and null.map is not working, but as i see this, why call updateData with null as second parameter if this is the expected new Bread Crumb ? [breadcrumb.component.ts:67](https://github.com/rajaramtt/ng7-dynamic-breadcrumb/blob/56300a6807253cc05718b2ee4284a3056eb92873/projects/ng-dynamic-breadcrumb/src/lib/ng-dynamic-breadcrumb.component.ts#L67)

Yes i know i have to define some breadcrumbs to get a better result, but i think it should not crash just because i dont have registered Breadcrumbs.

**Comment by r-hannuschka** [comment]
Well sry my mistake, i had an other breadcrumb module before, so breadcrumb was not an object it was a string and yes string.map will not work :D

But i think it should approve this before and not crash.

**Comment by rajaramtt** [comment]
@r-hannuschka   If possible Please create stackblitz example link!.

**Comment by dealenx** [comment]
I had the same error, I had a routing:
```
....
data: {
      breadcrumb: "My Page"
    }
....
```
The problem was resolved after this fix:
```
....
data: {
      title: "My Page",
      breadcrumb: [
        {
          label: "My Page",
          url: ""
        }
      ]
    }
....
```

**Comment by rajaramtt** [comment]
The issue has been fixed no need resolution
